version: '2'
services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - 3000:3000
    stdin_open: true  

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      MONGODB_URI: 'mongodb+srv://Ericuser1:un511FOcbFn6E5CG@clusterip6.3bdres3.mongodb.net/test'
      PORT: 5000
    ports:
      - 5000:5000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: Ericuser1
      MONGO_INITDB_ROOT_PASSWORD: un511FOcbFn6E5CG 
    ports:
      - 27017:27017




